package app.nzyme.plugin.distributed.tasksqueue;

public enum TaskType {

    TEST,

    PROVIDE_PGP_KEYS,

    PURGE_DATA_CATEGORY_GLOBAL,
    PURGE_DATA_CATEGORY_ORGANIZATION,
    PURGE_DATA_CATEGORY_TENANT,

    MONITOR_EXECUTION,

    TIMELINES_CALCULATION_DOT11_BSSID,
    TIMELINES_CALCULATION_DOT11_SSID,
    TIMELINES_CALCULATION_DOT11_CLIENT_CONNECTED,
    TIMELINES_CALCULATION_DOT11_CLIENT_DISCONNECTED

}
